---
- name: bind copy service to existing subject or create new subject with copy service
  hosts: test
  gather_facts: no
  connection: local

  vars:
    aci_login: &aci_login
      hostname: '{{ ansible_host }}'
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") | default(ansible_user, true) }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") | default(ansible_password, true) }}'
      validate_certs: no

  tasks:
  - name: Create a tenant
    aci_tenant:
      <<: *aci_login
      tenant: "{{ tenant_name }}"

  - name: Create Contracts
    aci_contract:
      <<: *aci_login
      tenant: "{{ tenant_name }}"
      contract: "{{ contract_name }}"

  - name: modify existing subject or add new subject to contract and bind copy service
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/tn-{{ tenant_name }}/brc-{{ contract_name }}.json
      method: post
      content:
        vzSubj:
          attributes:
            name: "{{ subject_name }}"
            status: "created,modified"
          children:
          - vzRsSubjGraphAtt:
              attributes:
                status: "created,modified"
                tnVnsAbsGraphName: "{{ service_graph }}"
