---
-  hosts: apic
   any_errors_fatal: "true"
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
     #t_name: 11-Ameen
     #vrf_name: 11-vrf 
     #ap_name: 11-ap

     bridgedomain:
       - { t_name: 'am-tn-1', bd_name: 'BD-101', status: created, vrf_name: 'am-vrf-1', ap_name: '11-ap', sub_ip: '10.10.0.1/24', bd_scope: private }
       - { t_name: 'am-tn-2', bd_name: 'BD-102', status: created, vrf_name: 'am-vrf-1', ap_name: '11-ap', sub_ip: '10.30.0.1/24', bd_scope: private }
       - { t_name: 'am-tn-3', bd_name: 'BD-103', status: created, vrf_name: 'am-vrf-1', ap_name: '11-ap', sub_ip: '10.20.0.1/24', bd_scope: public  }

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes

   tasks:
   - name: Set Credentials
     tags: always
     set_fact:
       cred: &cred
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         validate_certs: false



   - name: Create a tenant & AP
     aci_rest:
       <<: *cred  
       path: api/mo/uni.json
       method: post
       content:
         fvTenant:
           attributes:
             dn: uni/tn-{{ item.t_name }}
             status: created
           children:
             - fvBD:
                 attributes:
                   dn: uni/tn-{{ item.t_name }}/BD-{{ item.bd_name }}
                   arpFlood: "true"
                   name: "{{ item.bd_name }}"
                   rn: BD-{{ item.bd_name }}
                   status: created
                 children:
                  - fvSubnet:
                      attributes:
                        dn: uni/tn-{{ item.t_name }}/BD-{{ item.d_name }}/subnet-[{{ item.sub_ip }}]
                        ctrl: ""
                        ip: "{{ item.sub_ip }}"
                        rn: subnet-[{{ item.sub_ip }}]
                        scope: "{{ item.bd_scope }}"
                        status: created

             - fvCtx: 
                 attributes:
                   dn: uni/tn-{{ item.t_name }}/ctx-{{ item.vrf_name }}
                   name: "{{ item.vrf_name }}"
                   rn: ctx-{{ item.vrf_name }}
                   status: created
             - fvAp:
                 attributes:
                   dn: uni/tn-{{ item.t_name }}/ap-{{ item.ap_name }}
                   name: "{{ item.ap_name }}"
                   rn: ap-{{ item.ap_name }}
                   status: created
                 children:
                   - fvAEPg: 
                       attributes:
                         dn: uni/tn-{{ item.t_name }}/ap-{{ item.ap_name }}/epg-{{ item.epg_name }}
                         name: {{ item.epg_name }}
                         prio: level3
                         rn: epg-{{ item.epg_name }}
                         status: created
                       children:
                         - fvRsBd:
                             attributes:
                               tnFvBDName: {{ item.bd_name }}
                               status: modified
     
     loop: "{{ bridgedomain }}"
