---
-  hosts: apic
   any_errors_fatal: "true"
   gather_facts: no

   vars:
     ansible_connection: local
     #ansible_python_interpreter: /usr/bin/python3
     t_name: 11-Ameen
     vrf_name: 11-vrf 
     ap_name: 11-ap

     bridgedomain:
       - { tn_name: 'am-tn-1', name: 'BD-101', status: created, vrf: 'am-vrf-1' }
       - { tn_name: 'am-tn-2', name: 'BD-102', status: created, vrf: 'am-vrf-1' }
       - { tn_name: 'am-tn-3', name: 'BD-103', status: created, vrf: 'am-vrf-1' }

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes

   tasks:
   - name: Set Credentials
     tags: always
     set_fact:
       cred: &cred
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         validate_certs: false



   - name: Create a tenant & AP
     aci_rest:
       <<: *cred  
       path: api/mo/uni.json
       method: post
       content:
         fvTenant:
           attributes:
             dn: uni/tn-{{ t_name }}
             status: created
           children:
             - fvAp:
                 attributes:
                   dn: uni/tn-{{ t_name }}/ap-{{ ap_name }}
                   name: "{{ ap_name }}"
                   rn: ap-{{ ap_name }}
                   status: created
             - fvBD:
                 attributes:
                   dn: uni/tn-{{ t_name }}/BD-1-bd
                   arpFlood: "true"
                   name: 1-bd
                   rn: BD-1-bd
                   status: created
             - fvCtx: 
                 attributes:
                   dn: uni/tn-{{ t_name }}/ctx-{{ vrf_name }}
                   name: "{{ vrf_name }}"
                   rn: ctx-{{ vrf_name }}
                   status: created

             - fvAEPg: 
                 attributes:
                   dn: uni/tn-{{ t_name }}/ap-{{ ap_name }}/epg-2-epg
                   name: 2-epg
                   prio: level3
                   rn: epg-2-epg
                   status: created
                 children:
                 fvRsBd:
                   attributes:
                   tnFvBDName: 1-bd
                   status: created
