---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3

   vars_files:
     - coding_challenge_ansible.yml

   tasks:
   
   - name: Set Credentials
     set_fact:
       cred: &cred
         validate_certs: false
     
   - name: Create a tenant
     tags: tenant
     aci_tenant:
       tenant: "{{ item.name }}"
       description: "{{ item.description }}"
       <<: *cred
     with_items:
       - "{{ tenants }}"


   - name: Create ap
     tags: ap
     aci_ap:
       tenant: "{{ item.0.name  }}"
       name: "{{ item.1.name }}"
       description: "{{ item.1.description }}"
       <<: *cred
     with_subelements: 
       - "{{ tenants }}"
       - "application_profiles"

   - name: create VRF
     tags: vrf
     aci_vrf:
       vrf: "{{ item.1.name }}"
       tenant: "{{ item.0.name }}"
       <<: *cred
     with_subelements: 
       - "{{ tenants }}"
       - "vrfs"

# this iterates over three dictionaires 
   - name: Create three Bridge-Domains
     tags: bd
     aci_bd:
       tenant: "{{ item.0.name }}"
       bd: "{{ item.1.name }}"
       vrf: "{{ item.1.vrf }}"
       <<: *cred  
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"



   - name: Create three Subnets
     tags: subs
     aci_bd_subnet:
       tenant: "{{ item.0.name }}"
       name: "{{ item.1.subnets.0.name }}"          # Returns three names , coz bridge_domains has three different lists called "subnets".
       bd: "{{ item.1.name }}"                      # subnets.0 coz, ".subnets" retursn list of dictionaries, while ".subnets.0" retruns only the dict.
       gateway_ip: "{{ item.1.subnets.0.name }}"    # The process will be repeated 3 times, coz bridege_domains list has three "subnets" lists inside it. 
       subnet_mask: "{{ item.1.subnets.0.mask }}"   # To iterate over nested list of dictionaries, two level depth is the max
       scope: "{{ item.1.subnets.0.scope }}"        # Otherwise, you need to grab them one by one.
       <<: *cred 
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"


# epgs is sub-nested list, it has epg name, bd name then contracts list inside as well. 
   
   - name: Create EPG_Web_Server
     tags: epg
     aci_epg:
       tenant: "{{ item.0.name }}"
       ap: "{{ item.1.name }}"
       epg: "{{ item.1.epgs.0.name }}" # This returns one name, application_profiles has one list called epgs and it has nested dictionaries.
       bd: "{{ item.1.epgs.0.bd }}"    # that's why it wont be iterated upon, and epgs.0 must be specified. 
       <<: *cred                       # To iterate using "subelemenst", the output must be a dictionary.
     with_subelements:                 # alos, subelemenst, can iterrate over a dic and go two levels in depth, not more.
       - "{{ tenants }}"               # if epgs list is one level upper, it will work perfecly, just like we created three bridge domains
       - "application_profiles"


   - name: Create three Bridge-Domains
     tags: debug1
     debug:
       #msg: "{{ item.0.name }}"
       msg: "{{ item.1.name }}"
       #msg: "{{ item.1.vrf }}"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"


# Here I can grab the subnets details such as name, mask and scope for three subnets

   - name: Create three Bridge-Domains
     tags: debug2
     debug:
       #msg: "{{ item.0.name }}"
       msg: "{{ item.1.subnets }}" # returns the content of subnets,  list of dictonaries 
       #msg: "{{ item.1.vrf }}"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"


   - name: Create three Bridge-Domains
     tags: debug10
     debug:
       #msg: "{{ item.0.name }}"
       msg: "{{ item.1.subnets.0 }}" # returns the content of subnets,  list of dictonaries 
       #msg: "{{ item.1.vrf }}"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"


   - name: ce
     tags: debug3
     debug:
       #msg: "{{ item.0.name }}"
       msg:  "{{ item.1.subnets.name}}" # returns error, after that you need to specified with list you want .0 or .1 
       #msg: "{{ item.1.vrf }}"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"


# Repeated three times, coz epgs lies under application_profiles,
# There is only ap list
   - name: Create EPG_Web_Server
     tags: debug4
     debug:
       msg: "{{ item.1.epgs.0}}"   
     with_subelements:           
       - "{{ tenants }}"
       - "application_profiles"       # Repeated ones coz there is only ap list 

# Repeated three times, coz epgs lies under application_profiles,
# There is only ap list
   - name: Create EPG_Web_Server
     tags: debug5
     debug:
       msg: "{{ item.1.epgs}}"   # This returns one name, application_profiles has one list called epgs that's why it wont be iterated upon, and epgs.0 must be specified
     with_subelements:           # to iterte over dictionaries, the output has to be list of dictionaries 
       - "{{ tenants }}"
       - "application_profiles"       # Repeated ones coz there is only ap list 



   - name: Create three Subnets
     tags: debug6
     debug:
       msg: "{{ item.1.subnets.0 }}"          # Returns three dictionaries , coz bridge_domains has three different lists called "subnets"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"



   - name: debug7
     tags: debug7
     debug:
       msg: "{{ item.1.name}}"   
     with_subelements:            
       - "{{ tenants }}"
       - "epgs"


   - name: debug8
     tags: debug8
     debug:
       msg: "{{ item.1.name}}"   
     with_subelements:            
       - "{{ tenants }}"
       - "application_profiles"


   - name: with_subelements -> loop
     tags: debug9
     debug:
       msg: "{{ item.1.name }} "
     loop: "{{ tenants|subelements('epgs') }}"

