---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
    
   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes


   tasks:
   - name: Display the JSON file content
     tags: always
     shell: cat /root/tst_repo/source.json
     register: result

   - name: Set Credentials
     tags: always
     set_fact:
       cred: &cred
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         validate_certs: false

   - name: save the Json data to a Variable as a Fact
     tags: always
     set_fact:
       jsondata: "{{ result.stdout | from_json }}"


   - name: Create a tenant
     aci_tenant:
       tenant: "{{ item.name }}"
       description: "{{ item.description }}"
       <<: *cred  
     loop: "{{ jsondata  | json_query('tenants[*]') }}"


   - name: Create ap
     tags: debug1
     aci_ap:
       name: "{{ item.application_profiles.0.name }}"
       description: "{ item.application_profiles.description }}"
       tenant: "{{ item.name }}"
       <<: *cred  
     loop: "{{ jsondata | json_query('tenants[*]') }}"


   - name: create VRF
     tags: vrf
     aci_vrf:
       vrf: "{{ item.vrfs.0.name }}"
       tenant: "{{ item.name }}"
       <<: *cred  
     loop: "{{ jsondata | json_query('tenants[*]') }}"



   - name: Create three Bridge-Domains
     tags: bd
     debug: #aci_bd:
       #msg: "{{ item.name }}"  # name
       msg: "{{ item.bridge_domains }}"  # bd
       #msg: "{{ item.vrf.name }}"   # vrf
       #<<: *cred  
     loop: "{{ jsondata | json_query('tenants[*]') }}"





# output: -

# ok: [{{ apic_ip }}] => (item=[{u'name': u'datacenter'}]) => {
#    "ansible_loop_var": "item",
#    "item": [
#        {
#            "name": "datacenter"
#        }
#    ]
#}


#   - name: Display all cluster names
#     debug:
#      var: item.name
#     loop: "{{ jsondata  | json_query('tenants[*].vrfs') }}"


#ok: [{{ apic_ip }}] => (item=[{u'name': u'datacenter'}]) => {
#    "ansible_loop_var": "item",
#    "item": [
#        {
#            "name": "datacenter"
#        }
#    ],
#    "item.name": "VARIABLE IS NOT DEFINED!"
#}


    
# output: -

# ok: [{{ apic_ip }}] => (item=[{u'name': u'datacenter'}]) => {
#    "ansible_loop_var": "item",
#    "item": [
#        {
#            "name": "datacenter"
#        }
#    ]
#}



#   - name: Display 
#     debug:
#       var: "{{ jsondata  | json_query('tenants[*].vrfs.name') }}"

   

#   - name: Display 
#     debug:
#       var: item.name
#     loop: "{{ jsondata  | json_query('tenants.vrfs[*].name') }}"
