---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
     l3out_name: 'L3_Out_Device'
     epg_4: 'External_EPG'
     L3_domain: 'ISR3945'

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes

   vars_files:
     - coding_challenge_ansible.yml

   tasks:
   
   - name: Set Credentials
     set_fact:
       cred: &cred
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         validate_certs: false
     
   - name: Create a tenant
     tags: always
     aci_tenant:
       tenant: "{{ item.name }}"
       description: "{{ item.description }}"
       <<: *cred
     with_items:
       - "{{ tenants }}"


   - name: Create ap
     tags: ap
     aci_ap:
       tenant: "{{ item.0.name  }}"
       name: "{{ item.1.name }}"
       description: "{{ item.1.description }}"
       <<: *cred
     with_subelements: 
       - "{{ tenants }}"
       - "application_profiles"

   - name: create VRF
     tags: vrf
     aci_vrf:
       vrf: "{{ item.1.name }}"
       tenant: "{{ item.0.name }}"
       <<: *cred
     with_subelements: 
       - "{{ tenants }}"
       - "vrfs"


   - name: Create three Bridge-Domains
     tags: bd
     aci_bd:
       tenant: "{{ item.0.name }}"
       bd: "{{ item.1.name }}"
       vrf: "{{ item.1.vrf }}"
       <<: *cred  
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"



   - name: Create three Subnets
     tags: subs
     aci_bd_subnet:
       tenant: "{{ item.0.name }}"
       name: "{{ item.1.subnets.0.name }}"
       bd: "{{ item.1.name }}"
       gateway_ip: "{{ item.1.subnets.0.name }}"
       subnet_mask: "{{ item.1.subnets.0.mask }}"
       scope: "{{ item.1.subnets.0.scope }}"   
       <<: *cred 
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"


   - name: Create EPG_Web_Server
     tags: epg
     aci_epg:
       tenant: "{{ item.0.name }}"
       ap: "{{ item.1.name }}"
       epg: "{{ item.1.epgs.0.name }}"
       bd: "{{ item.1.epgs.0.bd }}"
       <<: *cred
     with_subelements: 
       - "{{ tenants }}"
       - "application_profiles"





   - name: Create three Bridge-Domains
     tags: debug, bds
     debug:
       #msg: "{{ item.0.name }}"
       msg: "{{ item.1.name }}"
       #msg: "{{ item.1.vrf }}"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"
